export const DriverModel = [
  {
    id: "identification",
    name: "Identification",
    type: "text",
    form: true,
    grid: true,
  },
  {
    id: "username",
    name: "Username",
    type: "text",
    form: true,
    grid: false,
  },
  {
    id: "name",
    name: "Name",
    type: "text",
    form: true,
    grid: true,
  },
  {
    id: "email",
    name: "Email",
    type: "email",
    form: true,
    grid: true,
  },
  {
    id: "password",
    name: "Password",
    type: "password",
    form: true,
    grid: false,
  },
  {
    id: "vehicle",
    name: "Vahicle",
    type: "text",
    form: true,
    grid: true,
  },
  {
    id: "plaque",
    name: "Plaque",
    type: "text",
    form: true,
    grid: true,
  },
  {
    id: "position",
    name: "Position",
    type: "position",
    form: true,
    grid: false,
  },
  {
    id: "distance",
    name: "Distance (Km)",
    type: "text",
    form: false,
    grid: true,
  },
  {
    id: "price",
    name: "Price ($)",
    type: "text",
    form: false,
    grid: true,
  },
  {
    id: "status",
    name: "Status",
    type: "select",
    options: [
      {
        name: "Active",
        value: "1",
      },
      {
        name: "Inactive",
        value: "0",
      },
    ],
    form: true,
    grid: false,
  },
  {
    id: "actions",
    name: "Actions",
    type: "text",
    form: false,
    grid: true,
  },
  {
    id: "childrens",
    name: "Childrens",
    children: {
      rolID: null,
    },
    form: false,
    grid: false,
  },
];
